defaults: &defaults
  users:
    dragon: slayer

  name: Hermes
  domain: postmonk.com
  
  juggernaut:
    host: maccman-hermes-rt.herokuapp.com

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
